routes/web.php
<?php

//Auth
Auth::routes(['register'=>false, 'verify'=>false]);
//Logged In
Route::middleware(['auth'])->group(function () {
    //Home
    Route::get('/', 'HomeController@index')->name('home');
    //Tags
    Route::get('tags', 'TagController@index')->name('tags');
    Route::get('tags-add', 'TagController@add')->name('tags.add');
    Route::post('tags-add', 'TagController@save')->name('tags.save');
    Route::get('tags-edit/{id}', 'TagController@edit')->name('tags.edit');
    Route::post('tags-edit/{id}', 'TagController@update')->name('tags.update');
    Route::get('tags-merge/{id}', 'TagController@merge')->name('tags.merge');
    Route::post('tags-merge/{id}', 'TagController@mergeSave')->name('tags.mergeSave');
    Route::get('tags-delete/{id}', 'TagController@delete')->name('tags.delete');
    //Authors
    Route::get('authors', 'AuthorController@index')->name('authors');
    Route::get('authors-add', 'AuthorController@add')->name('authors.add');
    Route::post('authors-add', 'AuthorController@save')->name('authors.save');
    Route::get('authors-edit/{id}', 'AuthorController@edit')->name('authors.edit');
    Route::post('authors-edit/{id}', 'AuthorController@update')->name('authors.update');
    Route::get('authors-delete/{id}', 'AuthorController@delete')->name('authors.delete');
    //Languages
    Route::get('languages', 'LanguageController@index')->name('languages');
    Route::get('languages-add', 'LanguageController@add')->name('languages.add');
    Route::post('languages-add', 'LanguageController@save')->name('languages.save');
    Route::get('languages-edit/{id}', 'LanguageController@edit')->name('languages.edit');
    Route::post('languages-edit/{id}', 'LanguageController@update')->name('languages.update');
    Route::get('languages-delete/{id}', 'LanguageController@delete')->name('languages.delete');
    //Publication Places
    Route::get('publication-places', 'PublicationPlaceController@index')->name('publicationPlaces');
    Route::get('publication-places-add', 'PublicationPlaceController@add')->name('publicationPlaces.add');
    Route::post('publication-places-add', 'PublicationPlaceController@save')->name('publicationPlaces.save');
    Route::get('publication-places-edit/{id}', 'PublicationPlaceController@edit')->name('publicationPlaces.edit');
    Route::post('publication-places-edit/{id}', 'PublicationPlaceController@update')->name('publicationPlaces.update');
    Route::get('publication-places-delete/{id}', 'PublicationPlaceController@delete')->name('publicationPlaces.delete');
    //Articles
    Route::get('articles', 'ArticleController@index')->name('articles');
    Route::get('articles-add', 'ArticleController@add')->name('articles.add');
    Route::post('articles-add', 'ArticleController@save')->name('articles.save');
    Route::get('articles-edit/{id}', 'ArticleController@edit')->name('articles.edit');
    Route::post('articles-edit/{id}', 'ArticleController@update')->name('articles.update');
    Route::get('articles-delete/{id}', 'ArticleController@delete')->name('articles.delete');
    //Stats
    Route::get('stats', 'StatsController@index')->name('stats');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['text'];

    public function getArticleCountAttribute()
    {
        return $this->hasMany('\App\Models\ArticleTag', 'tag_id', 'id')->count();
    }
}

app/Http/Controllers/StatsController.php
<?php

namespace App\Http\Controllers;

use App\Services\GeneralService;
use App\Services\StatsService;

class StatsController extends Controller
{
    private $general;

    private $stats;

    private $logs;

    public function __construct(GeneralService $general, StatsService $stats)
    {
        $this->general = $general;
        $this->stats = $stats;
    }

    public function index()
    {
        $this->general->setTitle('İstatistikler');
        $this->general->getUser();
        $this->stats->getYearStats();
        $this->stats->getTypeStats();
        $this->stats->getLanguageStats();
        $this->stats->getTagStats();
        $this->stats->returnStatsView();
    }
}

resources/views/stats/index.blade.php
@extends('layout')

@section('content')
    <div id="mainContent">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="bgc-white bd bdrs-3 ">
                        <div id="year_chart"></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="bgc-white bd bdrs-3 ">
                        <div id="type_chart"></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="bgc-white bd bdrs-3 ">
                        <div id="language_chart"></div>
                    </div>
                </div>
            </div>
            <div class="row mT-30">
                <div class="col-md-6">
                    <div class="bgc-white bd bdrs-3 ">
                        <div class="list-group">
                            @foreach($tag as $v)
                                <a href="{!! route('articles').'?tag='.$v->id !!}" class="list-group-item list-group-item-action">
                                    {!! $v->text !!}
                                    <span>({!! $v->article_count !!})</span>
                                </a>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footerAssets')
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {'packages': ['corechart']});
        google.charts.setOnLoadCallback(drawCharts);

        function drawCharts() {
            drawYearChart();
            drawTypeChart();
            drawLanguageChart();
        }

        function drawYearChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Year');
            data.addColumn('number', 'Total');
            data.addRows([
                    @foreach($year as $k=>$v)
                ['{!! $k !!}', {!! $v !!}],
                @endforeach
            ]);
            var options = {
                'title': 'Yıllara Göre Dağılım',
                'width': 400,
                'height': 300
            };
            var chart = new google.visualization.PieChart(document.getElementById('year_chart'));
            chart.draw(data, options);
        }

        function drawTypeChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Type');
            data.addColumn('number', 'Total');
            data.addRows([
                    @foreach($type as $k=>$v)
                ['{!! getConstantsAndReturnSelected('\App\Models\Article',$k) !!}', {!! $v !!}],
                @endforeach
            ]);
            var options = {
                'title': 'Türlere Göre Dağılım',
                'width': 400,
                'height': 300
            };
            var chart = new google.visualization.PieChart(document.getElementById('type_chart'));
            chart.draw(data, options);
        }

        function drawLanguageChart() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Dil');
            data.addColumn('number', 'Total');
            data.addRows([
                    @foreach($language as $k=>$v)
                ['{!! $k !!}', {!! $v !!}],
                @endforeach
            ]);
            var options = {
                'title': 'Dillere Göre Dağılım',
                'width': 400,
                'height': 300
            };
            var chart = new google.visualization.PieChart(document.getElementById('language_chart'));
            chart.draw(data, options);
        }
    </script>
@endsection